version: '3.8'

services:
  jupyter:
    build: .

    # Mount to Dropbox
    volumes:
      - C:\Dropbox\Projects\Dotmagic\:/app
      - //var/run/docker.sock:/var/run/docker.sock

    # External:Internal
    ports:
      - "8888:8888"
